# Generated by Django 5.0.6 on 2024-07-10 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('content', models.TextField(max_length=600)),
                ('image', models.ImageField(upload_to='image')),
            ],
        ),
    ]
