# Generated by Django 5.0.6 on 2024-08-04 15:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('whatsapp', models.CharField(max_length=300)),
                ('users', models.ManyToManyField(blank=True, related_name='cohorts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
