# Generated by Django 5.0.6 on 2024-06-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_time',
            field=models.DateTimeField(null=True),
        ),
    ]
