# Generated by Django 5.0.6 on 2024-06-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_otp_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
