# Generated by Django 5.0.6 on 2024-06-24 20:18

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_otp_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dp_no',
            field=models.CharField(default=user.models.generate_otp, editable=False, max_length=200, unique=True),
        ),
    ]
