# Generated by Django 5.0.6 on 2024-06-24 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_dp_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dp_no',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
