# Generated by Django 5.0.6 on 2024-07-31 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_courselist'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='course',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='courselist', to='user.courselist'),
            preserve_default=False,
        ),
    ]
