# Generated by Django 4.2.14 on 2024-08-04 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_user_otp_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='passcode',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
