# Generated by Django 5.0.6 on 2024-09-22 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_profile_passcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='suspension',
            field=models.BooleanField(default=False),
        ),
    ]
