# Generated by Django 5.0.6 on 2024-09-09 10:14

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_student_project_task_required_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_project',
            name='project_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='project_id395533', editable=False, length=10, max_length=20, prefix='project_id', unique=True),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='task_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='task_id34905', editable=False, length=10, max_length=20, prefix='task_id', unique=True),
        ),
    ]
