# Generated by Django 5.0.6 on 2024-09-10 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_student_project_project_id_tasksubmission_task_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_project',
            name='status',
        ),
        migrations.CreateModel(
            name='UserProjectStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'completed'), ('progress', 'progress')], default='pending', max_length=20)),
                ('projects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='projects.student_project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_status', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
