# Generated by Django 5.0.6 on 2024-09-13 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_student_project_status_userprojectstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_project',
            name='url',
        ),
    ]
