# Generated by Django 5.0.6 on 2024-09-22 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_monthlyscoreallocation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlyscoreallocation',
            old_name='cohort',
            new_name='user',
        ),
    ]
